# Inverter Grid Test

In [44]:
import villas.dataprocessing.readtools as rt
import villas.dataprocessing.plottools as pt
from villas.dataprocessing.timeseries import TimeSeries
import matplotlib.pyplot as plt

In [45]:
# read results
work_dir = '../../../logs/DP_Inverter_Grid_Test/'
log_name = 'DP_Inverter_Grid_Test'
print(work_dir + log_name + '.csv')

ts_dpsim = rt.read_timeseries_dpsim(work_dir + log_name + '.csv')

../../../logs/DP_Inverter_Grid_Test/DP_Inverter_Grid_Test.csv
column number: 31
results length: 10001
real column names: []
complex column names: ['i12', 'i34', 'v1', 'v1_1', 'v1_10', 'v1_11', 'v1_12', 'v1_2', 'v1_3', 'v1_4', 'v1_5', 'v1_6', 'v1_7', 'v1_8', 'v1_9', 'v2', 'v3', 'v3_1', 'v3_10', 'v3_11', 'v3_12', 'v3_2', 'v3_3', 'v3_4', 'v3_5', 'v3_6', 'v3_7', 'v3_8', 'v3_9', 'v4', 'v5']


In [46]:
ts_dpsim['v1'].values

array([0.-313.2j, 0.-313.2j, 0.-313.2j, ..., 0.-313.2j, 0.-313.2j,
       0.-313.2j])

In [47]:
ts_list_v1 = [
    ts_dpsim['v1'], 
    ts_dpsim['v1_1'],
    ts_dpsim['v1_2'],
    ts_dpsim['v1_3'],
    ts_dpsim['v1_4'],
    ts_dpsim['v1_5'],
    ts_dpsim['v1_6'],
    ts_dpsim['v1_7'],
    ts_dpsim['v1_8'],
    ts_dpsim['v1_9'],
    ts_dpsim['v1_10'],
    ts_dpsim['v1_11'],
    ts_dpsim['v1_12']]

ts_list_v3 = [
    ts_dpsim['v3'], 
    ts_dpsim['v3_1'],
    ts_dpsim['v3_2'],
    ts_dpsim['v3_3'],
    ts_dpsim['v3_4'],
    ts_dpsim['v3_5'],
    ts_dpsim['v3_6'],
    ts_dpsim['v3_7'],
    ts_dpsim['v3_8'],
    ts_dpsim['v3_9'],
    ts_dpsim['v3_10'],
    ts_dpsim['v3_11'],
    ts_dpsim['v3_12']]

freq_list = [
    50,
    19750,
    19850,
    19950,
    20050,
    20150,
    20250,
    39750,
    39850,
    39950,
    40050,
    40150,
    40250]

In [48]:
ts_dpsim_emt_v1 = TimeSeries.create_emt_from_dp(ts_list_v1, freq_list)
ts_dpsim_emt_v1.values

array([ 0.00000000e+00, -8.06564629e-01,  6.03489020e+00, ...,
       -6.03489020e+00,  8.06564629e-01, -7.99766086e-11])

In [25]:
%matplotlib qt
pt.plot_timeseries(1, ts_dpsim_emt_v1)
plt.xlim(0, 0.05)

(0, 0.05)

In [49]:
ts_dpsim_emt_v3 = TimeSeries.create_emt_from_dp(ts_list_v3, freq_list)
ts_dpsim_emt_v3.values

array([-1.66810000e-02, -1.46754790e-02,  1.95348710e-02, ...,
       -2.22675535e+01, -2.14527875e+01, -2.06349310e+01])

In [ ]:
%matplotlib qt
pt.plot_timeseries(1, ts_dpsim_emt_v3)
plt.xlim(0, 0.05)

In [50]:
ts_dpsim_emt_v5 = ts_dpsim['v5'].frequency_shift(50)

In [51]:
%matplotlib qt
pt.plot_timeseries(1, ts_dpsim_emt_v1)
pt.plot_timeseries(1, ts_dpsim_emt_v3)
pt.plot_timeseries(1, ts_dpsim_emt_v5)
plt.xlim(0, 0.05)

(0, 0.05)

In [52]:
ts_dpsim_emt_v1 = ts_dpsim['v1'].frequency_shift(50)
pt.plot_timeseries(1, ts_dpsim_emt_v1)
plt.xlim(0, 0.05)

(0, 0.05)

In [43]:
import numpy as np
from villas.dataprocessing.timeseries import TimeSeries
timeseries_list = ts_list
freqs_list = freq_list

new_timeseries_list = []
#new_timeseries_list.append(timeseries_list[0])
for i in range(0, len(timeseries_list)):
    tmp = timeseries_list[i].scale(ts.name, -1j)
    new_timeseries_list.append(tmp)

In [44]:
new_timeseries_list[0].values

array([0.-313.2j, 0.-313.2j, 0.-313.2j, ..., 0.-313.2j, 0.-313.2j,
       0.-313.2j])

In [45]:
new_timeseries_list[1].values

array([0.-6.619798j, 0.-6.619798j, 0.-6.619798j, ..., 0.-6.619798j,
       0.-6.619798j, 0.-6.619798j])

In [51]:
result = np.zeros_like(new_timeseries_list[0].values)
for ts, freq in zip(new_timeseries_list, freqs_list):
    ts_emt = ts.frequency_shift(freq)
    result = result + ts_emt.values
ts_result = TimeSeries('emt', new_timeseries_list[0].time, result)

In [52]:
%matplotlib qt
pt.plot_timeseries(1, ts_result)
plt.xlim(0, 0.05)

(0, 0.05)

In [41]:
result = np.zeros_like(timeseries_list[0].values)
for ts, freq in zip(timeseries_list, freqs_list):
    ts_emt = ts_shift = TimeSeries(ts.name, ts.time, ts.values.real*np.sin(2*np.pi*freq*ts.time))
    result = result + ts_emt.values
ts_result = TimeSeries('emt', timeseries_list[0].time, result)

In [42]:
%matplotlib qt
pt.plot_timeseries(1, ts_result)
plt.xlim(0, 0.05)

(0, 0.05)